<?php

declare(strict_types=1);

return [
    'initial_balance' => (int) env('CASINO_INITIAL_BALANCE', 1000),
    'bet_limits' => [
        'min' => (int) env('CASINO_MIN_BET', 1),
        'max' => (int) env('CASINO_MAX_BET', 10000),
    ],
    'catalog' => [
        [
            'slug' => 'coinflip',
            'route' => 'casino.coinflip',
            'name' => 'Coinflip',
            'code' => '01',
            'category' => 'sorte',
            'tag' => 'ORIGINAL',
            'label' => 'Cara ou coroa',
            'blurb' => 'Escolha um lado, prepare o compromisso e lance a moeda.',
            'icon' => '◎',
        ],
        [
            'slug' => 'dice',
            'route' => 'casino.dice',
            'name' => 'Dados',
            'code' => '02',
            'category' => 'dados',
            'tag' => 'ORIGINAL',
            'label' => 'Abaixo ou acima',
            'blurb' => 'Defina o limite, o lado da curva e deixe o dado decidir.',
            'icon' => '⚄',
        ],
        [
            'slug' => 'roulette',
            'route' => 'casino.roulette',
            'name' => 'Roleta europeia',
            'code' => '03',
            'category' => 'mesas',
            'tag' => 'MESA',
            'label' => 'Roda de zero único',
            'blurb' => 'Apostas internas e externas numa roda clássica de 37 casas.',
            'icon' => '◉',
        ],
        [
            'slug' => 'blackjack',
            'route' => 'casino.blackjack',
            'name' => 'Blackjack',
            'code' => '04',
            'category' => 'cartas',
            'tag' => 'MESA',
            'label' => 'Pedir, parar ou dobrar',
            'blurb' => 'Chegue o mais perto possível de 21 sem ultrapassar o dealer.',
            'icon' => '♠',
        ],
        [
            'slug' => 'slots',
            'route' => 'casino.slots',
            'name' => 'Slots',
            'code' => '05',
            'category' => 'sorte',
            'tag' => 'ORIGINAL',
            'label' => '6 linhas: 3 horizontais e 3 verticais',
            'blurb' => 'Grelha 3×3 com 3 linhas horizontais e 3 verticais. Três símbolos iguais numa linha pagam.',
            'icon' => '✦',
        ],
        [
            'slug' => 'jetx',
            'route' => 'casino.jetx',
            'name' => 'JetX',
            'code' => '06',
            'category' => 'sorte',
            'tag' => 'ORIGINAL',
            'label' => 'Foguete em ascensão',
            'blurb' => 'Lança o foguete, acompanha o multiplicador e recolhe antes do crash.',
            'icon' => '🚀',
        ],
    ],
    'games' => [
        'coinflip' => ['house_edge_bps' => 250],
        'dice' => [
            'house_edge_bps' => 500,
            'target_rtp_basis_points' => 9500,
        ],
        'jetx' => [
            'target_rtp_basis_points' => 9700,
            'starting_multiplier' => 1.00,
            'max_multiplier' => 2500.00,
            'multiplier_time_constant_ms' => 6500,
            'crash_precision' => 2,
            'instant_crash_probability_basis_points' => 300,
        ],
        'slots' => [
            'rows' => 3,
            'columns' => 3,
            'symbol_count' => 8,
            'paylines' => [
                ['direction' => 'horizontal', 'index' => 0],
                ['direction' => 'horizontal', 'index' => 1],
                ['direction' => 'horizontal', 'index' => 2],
                ['direction' => 'vertical', 'index' => 0],
                ['direction' => 'vertical', 'index' => 1],
                ['direction' => 'vertical', 'index' => 2],
            ],
            'variants' => [
                'classic' => [
                    'name' => 'Allin Classic',
                    'tag' => 'FRUIT · RETRO',
                    'icon' => '🍒',
                    'description' => 'Fruta clássica, campainhas e 7.',
                    'symbols' => ['🍒', '🍋', '🍊', '🔔', '⭐', '🍀', '💎', '7️⃣'],
                    'paytable' => [4, 8, 12, 20, 45, 70, 110, 180],
                ],
                'neon' => [
                    'name' => 'Neon Pulse',
                    'tag' => 'CYBER · NEON',
                    'icon' => '⚡',
                    'description' => 'Símbolos eléctricos, alienígenas e energia digital.',
                    'symbols' => ['⚡', '🔮', '👾', '🪐', '💥', '🧿', '🛸', '🌌'],
                    'paytable' => [4, 7, 11, 18, 30, 55, 100, 240],
                ],
                'gems' => [
                    'name' => 'Gem Royale',
                    'tag' => 'GEMS · ROYAL',
                    'icon' => '💎',
                    'description' => 'Diamantes, coroas e tesouros de alto valor.',
                    'symbols' => ['💎', '🔷', '🔶', '💠', '👑', '💰', '🪙', '🏆'],
                    'paytable' => [3, 6, 10, 16, 28, 50, 95, 300],
                ],
                'candy' => [
                    'name' => 'Candy Pop',
                    'tag' => 'SWEET · POP',
                    'icon' => '🍭',
                    'description' => 'Doces, bolos e fruta numa máquina colorida.',
                    'symbols' => ['🍭', '🍬', '🍩', '🧁', '🍓', '🍒', '🍰', '🍫'],
                    'paytable' => [4, 8, 13, 21, 38, 65, 105, 210],
                ],
                'space' => [
                    'name' => 'Space 777',
                    'tag' => 'SPACE · 777',
                    'icon' => '🚀',
                    'description' => 'Uma máquina cósmica com planetas e naves.',
                    'symbols' => ['🚀', '🪐', '🌙', '⭐', '☄️', '👽', '🛸', '🌌'],
                    'paytable' => [3, 7, 12, 20, 36, 70, 125, 350],
                ],
                'wild' => [
                    'name' => 'Wild Gold',
                    'tag' => 'WILD · GOLD',
                    'icon' => '🐺',
                    'description' => 'Animais selvagens, fogo e prémios de ouro.',
                    'symbols' => ['🐺', '🦊', '🦁', '🐯', '🦂', '🐍', '🌵', '🔥'],
                    'paytable' => [3, 6, 10, 17, 30, 58, 120, 500],
                ],
            ],
            'target_rtp_basis_points' => 9520,
            'bonus_buy' => [
                'enabled' => true,
                'options' => [
                    ['multiplier' => 10, 'spins' => 10, 'label' => 'Mini Bónus'],
                    ['multiplier' => 25, 'spins' => 20, 'label' => 'Mega Bónus'],
                    ['multiplier' => 50, 'spins' => 35, 'label' => 'Ultra Bónus'],
                ],
            ],
        ],
    ],
];
